server:
  port: 9090
  
turbine:
  app-config: user-service, payment-service
  cluster-name-expression: new String("default")
  
management:
  server:
    port: 8990
  
spring:
  application:
    name: monitoring
  
eureka:  
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



    
    
