eureka:  
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: payment-service    
    
    
server:
  port: 8383
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
        - mappings
        
        
logging:
  file: payment.log  
  path: /opt/                