eureka:  
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: payment-service    
    
    
server:
  port: 8383
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
        - mappings
        
        
logging:
  file: payment.log  
  path: /opt/
  
  
feign:
 client:
  config:
   default:
    connectTimeout: 60000           
    readTimeout: 60000
    

    
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 6000                      
  