eureka:  
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    instance-id: configserver
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
        
      
spring:
  application:
    name: configserver
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: file://${user.home}/conf
          basedir:
            file://${user.home}/conf
        native:
          search-locations:
          - file://${user.home}/conf
  profiles:
    active:
    - native
    
server:
  port: 8888    
           
           