eureka:  
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: user-service
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
           